# Generated by Django 4.2.4 on 2023-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
