# Generated by Django 4.2.4 on 2023-08-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0002_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip'),
            preserve_default=False,
        ),
    ]
