# Generated by Django 4.2.4 on 2023-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0003_activity_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination',
        ),
    ]
