# Generated by Django 4.2.4 on 2023-08-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0004_remove_activity_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254, unique=True)),
                ('state', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.user')),
            ],
        ),
    ]
