# Generated by Django 4.2.4 on 2023-08-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0005_alter_activity_id_alter_trip_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(verbose_name='departure date'),
        ),
    ]
