# Generated by Django 4.2.4 on 2023-08-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelGroup', '0006_alter_trip_arrival_date_alter_trip_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(to='travelGroup.user'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Activity Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip', verbose_name="Trip's Activity"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipient',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.user', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.BooleanField(default=False, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelGroup.trip', verbose_name="Trip's Invitation"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=64, verbose_name='Trip Destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Trip Name'),
        ),
    ]
